# src\PMM\PlatformBundle\Resources\config

services:
    pmm_platform.antispam:
        class: PMM\PlatformBundle\PMMAntispam\PMMAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50
            
services:
    pmm_platform.email.application_mailer:
        class: PMM\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"
            
services:
    pmm_platform.doctrine_listener.application_creation:
        class: PMM\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@pmm_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

services:
    pmm_platform.purger.advert:
        class: PMM\PlatformBundle\PMMPurger\PMMPurger