# src/PMM/PlatformBundle/Resources/config

services:
    pmm_platform.purger.advert:
        class: PMM\PlatformBundle\Purger\PMMPurger
        arguments:
            -"@doctrine.orm.entity_manager"

    pmm_platform.antispam:
        class: PMM\PlatformBundle\PMMAntispam\PMMAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50

    pmm_platform.email.application_mailer:
        class: PMM\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    pmm_platform.doctrine_listener.application_creation:
        class: PMM\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@pmm_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }
