# src/PMM/PlatformBundle/Resources/config

services:
    pmm_platform.antispam:
        class: PMM\PlatformBundle\PMMAntispam\PMMAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50

    pmm_platform.email.application_mailer:
        class: PMM\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    pmm_platform.doctrine_listener.application_creation:
        class: PMM\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@pmm_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    pmm_platform.purger.advert:
        class: PMM\PlatformBundle\PurgerAdvert\PMMPurgerAdvert
        arguments:
            - "@doctrine.orm.entity_manager"

    pmm_platform.validator.antiflood:
        class: PMM\PlatformBundle\Validator\AntifloodValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: pmm_platform_antiflood}