<?php

namespace PMM\PlatformBundle\Repository;

/**
 * AdvertCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
