<?php

namespace PMM\UserBundle\Repository;

/**
 * entityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entityRepository extends \Doctrine\ORM\EntityRepository
{
}
