#src/PMM/CoreBundle/Resources/config/routing.yml

pmm_home:
    path:    /
    defaults:
        _controller: PMMCoreBundle:Home:index
        
pmm_contact:
    path:    /contact
    defaults:
        _controller: PMMCoreBundle:Home:contact